### PR TITLE
Updated packages to latest working versions

### PR DESCRIPTION
**Pull request by IgniparousTempest**

### CODE REVIEW

**Comment by ishaan1995** [comment]
Why isn't this being merged to code. It does help right? @expbot . Taking too much time to merge a small change.

**Comment by ishaan1995** [comment]
@brentvatne ^ Look into this.

**Comment by brentvatne** [comment]
I'm going to delete this repository as we cannot maintain examples for every possible library out there, I believe that nativebase provides an example of how to do this in their own repo now: https://github.com/GeekyAnts/NativeBase#4-getting-started -- under the CRNA / Expo section

**Comment by brentvatne** [comment]
thanks for doing this -- we're not going to maintain this repository so I changed the README to just point to the NativeBase README: https://github.com/expo/nativebase-example/blob/master/README.md

**Pull request closed without merging**
